
name: Build and Deploy to Cloud Run

on:
  push:
    paths:
    - 'RELEASE.version'

env:
  PROJECT_ID: '${{ secrets.PROJECT_ID }}' # TODO: update Google Cloud project id.
  GAR_LOCATION: '${{ secrets.GAR_LOCATION }}' # TODO: update Artifact Registry location
  SERVICE: '${{ secrets.SERVICE_NAME }}' # TODO: update Cloud Run service name
  REGION: '${{ secrets.SERVICE_REGION }}' # TODO: update Cloud Run service region
  DOCKER_USER: '${{ secrets.DOCKER_AUTH_USER }}'
  APP_NAME: '${{ secrets.APP_NAME }}'
  CLOUD_RUN_NAME: '${{ secrets.CLOUD_RUN_NAME }}'

jobs:
  build:
    # Add 'id-token' with the intended permissions for workload identity federation
    permissions:
      contents: write
      id-token: write

    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Read VERSION file
        id: getversion
        run: echo "::set-output name=version::$(cat RELEASE.version)"
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: ${{ steps.getversion.outputs.version }}
          prerelease: false    

      - name: Google Auth
        id: auth
        uses: 'google-github-actions/auth@v0'
        with:
          token_format: 'access_token'
          workload_identity_provider: '${{ secrets.WIF_PROVIDER }}' 
          service_account: '${{ secrets.WIF_SERVICE_ACCOUNT }}'

      - name: Login to GAR
        uses: docker/login-action@v2
        with:
          registry: ${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.PROJECT_ID }}
          username: oauth2accesstoken
          password: ${{ steps.auth.outputs.access_token }}

      - name: Build and Push Container
        shell: bash
        env: 
          GAR_LOCATION: '${{ secrets.GAR_LOCATION }}'
          SERVICE: '${{ secrets.SERVICE_NAME }}'
          PROJECT_ID: '${{ secrets.PROJECT_ID }}'
          
        run: |-
          docker build -t europe-west1-docker.pkg.dev/hdruk-gateway-dev/hdruk-gateway/${{ steps.getversion.outputs.version }}:${{ github.sha }} ./
          docker push europe-west1-docker.pkg.dev/hdruk-gateway-dev/hdruk-gateway/${{ steps.getversion.outputs.version }}:${{ github.sha }} 

      # END - Docker auth and build



































      # Deployment please don't modify anything here as the infrastructure is controlled by terraform any changes here please agree with chris and reuben
  deploy:
    needs: build
    permissions:
      contents: write
      id-token: write

    runs-on: ubuntu-latest
    environment: dev-legacy
    steps:
      - name: Google Auth
        id: auth
        uses: 'google-github-actions/auth@v0'
        with:
          token_format: 'access_token'
          workload_identity_provider: '${{ secrets.WIF_PROVIDER }}' 
          service_account: '${{ secrets.WIF_SERVICE_ACCOUNT }}'
          
      - name: Deploy to Cloud Run
        uses: actions-hub/gcloud@master
        id: deploy
        env:
          PROJECT_ID: '${{ secrets.PROJECT_ID }}'
        with:
          args: run services update '${{ env.APP_NAME }}' --image=${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/hdruk-gateway/${{ steps.getversion.outputs.version }}:${{ github.sha }}
      # If required, use the Cloud Run url output in later steps